# Generated by Django 5.2 on 2025-11-09 02:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('ma_danh_muc', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã danh mục')),
                ('ten_danh_muc', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'danh_muc',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('sdt', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Số điện thoại')),
                ('dia_chi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'khach_hang',
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã sách')),
                ('ten_sach', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('nha_xuat_ban', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà xuất bản')),
                ('tac_gia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tác giả')),
                ('gia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá')),
                ('mo_ta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'sach',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('ma_hoa_don', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã hóa đơn')),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền')),
                ('ngay_lap', models.DateField(auto_now_add=True, verbose_name='Ngày lập')),
                ('tinh_trang', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('dang_chuan_bi', 'Đang chuẩn bị'), ('dang_giao', 'Đang giao'), ('da_giao', 'Đã giao'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=50, verbose_name='Tình trạng')),
                ('sdt_khach_hang', models.ForeignKey(db_column='sdt_khach_hang', on_delete=django.db.models.deletion.CASCADE, to='bookshop.khachhang', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'don_hang',
                'ordering': ['-ngay_lap'],
            },
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_khuyen_mai', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã khuyến mãi')),
                ('gia_khuyen_mai', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khuyến mãi')),
                ('ngay_bat_dau', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('ma_sach', models.ForeignKey(db_column='ma_sach', on_delete=django.db.models.deletion.CASCADE, related_name='khuyen_mai', to='bookshop.sach', verbose_name='Mã sách')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
                'db_table': 'khuyen_mai',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('ma_chi_tiet', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã chi tiết')),
                ('ten_sach', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('so_luong', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('mo_ta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả')),
                ('ma_hoa_don', models.ForeignKey(db_column='ma_hoa_don', on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='bookshop.donhang', verbose_name='Mã hóa đơn')),
                ('ma_sach', models.ForeignKey(db_column='ma_sach', on_delete=django.db.models.deletion.CASCADE, to='bookshop.sach', verbose_name='Mã sách')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'chi_tiet_don_hang',
            },
        ),
        migrations.CreateModel(
            name='SachDanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_danh_muc', models.ForeignKey(db_column='ma_danh_muc', on_delete=django.db.models.deletion.CASCADE, to='bookshop.danhmuc', verbose_name='Mã danh mục')),
                ('ma_sach', models.ForeignKey(db_column='ma_sach', on_delete=django.db.models.deletion.CASCADE, to='bookshop.sach', verbose_name='Mã sách')),
            ],
            options={
                'verbose_name': 'Sách - Danh mục',
                'verbose_name_plural': 'Sách - Danh mục',
                'db_table': 'sach_danh_muc',
                'unique_together': {('ma_sach', 'ma_danh_muc')},
            },
        ),
    ]
