# Generated by Django 5.2.8 on 2025-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_sach_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='mo_ta',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Mô tả'),
        ),
    ]
