# Generated by Django 5.2.8 on 2025-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_danhmuc_mo_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khuyenmai',
            name='ma_khuyen_mai',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã khuyến mãi'),
        ),
    ]
